### ISSUE TITLE
ImportError: No module named splinter

### ISSUE THREAD

**Issue by realowded** [jansenicus/www-coursera-downloader#15]
That's the error message i got and i have downloaded the splinter.

I know it directory issue, can anyone guide me?

**Comment by bdalal** [comment]
check the site-packages directory of your python install to see if splinter is present otherwise install it with either pip or manually.

**Comment by analyticbastard** [comment]
I solved this by `pip install --user splinter` and avoided dealing with any permission stuff whatsoever.
