### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by MR-T77** [jansenicus/www-coursera-downloader#21]
When I try to run I get this error

**Comment by MR-T77** [comment]
RuntimeError: Bad magic number in .pyc file

**Comment by matteosotti** [comment]
Mee too

**Comment by lahcene47** [comment]
Me too. but fixed after figuring out that I have installed Anaconda3 rather than Anaconda2.
you have to make sure that you install either Anaconda2 or Miniconda2  (not Anaconda3 or Miniconda3)
