### ISSUE TITLE
how the hell am I supposed to use this shit 

### ISSUE THREAD

**Issue by ahmed56734** [jansenicus/www-coursera-downloader#29]

**Comment by ghjsdka** [comment]
Just found an easy to use script on git. Just enter the course you want to download and it is done. https://github.com/bcbcbcbcbcl/working-coursera-download-with-selenium

**Comment by pahiwiw** [comment]
try this out, easy to setup and download
https://github.com/bcbcbcbcbcl/working-coursera-download-with-selenium
